sudo: false
language: cpp
compiler:
    - gcc
    - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-4.9
    - g++-4.9
    - cmake
    - libgfortran3
    - gfortran
    - libopenmpi-dev
    - openmpi-bin
    - libblas-dev
    - liblapack-dev
    - libfftw3-dev
    - libgmp-dev
    - libhdf5-serial-dev
    - libboost1.55-all-dev
deploy:
  provider: s3
  access_key_id: $AWS_A_KEY
  secret_access_key: $AWS_S_KEY
  bucket: buildbin
  skip_cleanup: true
  region: us-west-2
  endpoint: s3-us-west-2.amazonaws.com
  local_dir: $HOME/bin
  on:
    branch: travis

before_install:
    - if [ "$CXX" == "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

    #Set anaconda python environment
    - cd $HOME
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda
    - conda create --yes -n testenv python=2.7 numpy scipy matplotlib tornado pyzmq cython h5py pip
    - source activate testenv
    - pip install mako mpi4py
    - wget https://s3-us-west-2.amazonaws.com/buildbin/triqs_$CXX.tar.bz2
    - tar -C / -jvxf triqs_$CXX.tar.bz2
    - export LD_LIBRARY_PATH=$HOME/lib/lib:$LD_LIBRARY_PATH
    - export PYTHONPATH=$HOME/lib/lib/python2.7/site-packages:$PYTHONPATH
    - export OPENBLAS_NUM_THREADS=1


install:
    - mkdir -p $HOME/_build
    - cd $HOME/_build
    - cmake -DTRIQS_PATH=$HOME/lib/ $TRAVIS_BUILD_DIR
    - make -j4

script:
    - make test
    - make install
    - mkdir $HOME/bin
    - tar -jvcf $HOME/bin/cthyb_t_$CXX.tar.bz2 $HOME/lib